### ISSUE TITLE
test src/lib.rs - Adler32 (line 57) ... FAILED (on s390x, big endian)

### ISSUE THREAD

**Issue by decathorpe** [jonas-schievink/adler#8]
```
---- src/lib.rs - Adler32 (line 57) stdout ----
Test executable failed (exit code 101).
stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `857672080`,
 right: `859900304`', src/lib.rs:19:1
```

I'm unsure why this would fail on s390x (the only big-endian architecture I have access to).
Maybe because the `big: u64` field in the `Data` struct has a different byte order there?

**Comment by jonas-schievink** [comment]
>  Maybe because the `big: u64` field in the `Data` struct has a different byte order there?

Yeah, looks like it: https://doc.rust-lang.org/src/core/hash/mod.rs.html#301-303

Not sure what the best fix is, maybe just check against 2 different checksums depending on the target endianness?

**Comment by decathorpe** [comment]
Thanks for the quick answer! If that assertion can be cfg'd depending on endianness, that should fix the problem.

According to the rust docs ( https://doc.rust-lang.org/reference/conditional-compilation.html#target_endian ) maybe something like this should do the trick?

```
#[cfg(target_endian = "little")]
assert_eq!(adler.checksum(), 0x33410990);
#[cfg(target_endian = "big")]
assert_eq!(adler.checksum(), 0x331F0990);
```

(please check that I didn't do copypasta the second hex value ...)

---

EDIT: Can confirm that the above works (tested on x86_64 and s390x).

**Comment by jonas-schievink** [comment]
Yeah that seems good! Perhaps use `cfg!` instead of `#[cfg]` though, so both branches are typechecked independent on endianness.
